
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from "react";

export default function FlagCR(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAbUExURdMYL+AcNAQvgP7+/vLy8gQxhgUziwU1jgY1j5qGDksAAAChSURBVDjL7ZQxDsMgDADtH8APqkrZK/UDHfqAConOWeL8IM3YLd+uwS4hjWRlReohbGwfjMDyKszzUlXSeQMRjeM0UWFb9UA2PUSbxyo847DJOyHGLseg+SucV4LGUPVOtfBDl0xL0BeuNpc2BG/j2hAc4xGRg0cnVd5aAc8wWRxQSAdwucnzfEKQjqw0KndASAajBrTH3ebWhvD/o479UR/BORULDpwq7wAAAABJRU5ErkJggg=="
      alt="CR"
      {...props}
    />
  );
}
