export const COLUMNS = Object.freeze({
  ANCHOR: "ANCHOR",
  BOOLEAN: "BOOLEAN",
  CATEGORICAL: "CATEGORICAL",
  CUSTOM: "CUSTOM",
  DATETIME: "DATETIME",
  NUMERICAL: "NUMERICAL",
  ROW_INDEX: "ROW_INDEX",
  STRING: "STRING",
});
export const NUMERICAL_FORMATS = Object.freeze({
  DEFAULT: "DEFAULT",
  ACCOUNTING: "ACCOUNTING",
  PERCENTAGE: "PERCENTAGE",
});
export const DATETIME_OPERATIONS = Object.freeze({
  RANGE_DATETIME: "RANGE_DATETIME",
  RANGE_DATE: "RANGE_DATE",
  RANGE_TIME: "RANGE_TIME",
  WEEKDAY: "WEEKDAY",
  MONTH: "MONTH",
  QUARTER: "QUARTER",
  HALF: "HALF",
  YEAR: "YEAR",
});
export const SORT_DIRECTIONS = Object.freeze({
  ASC: "ASC",
  DESC: "DESC",
});
export const FILTER_SHELL_WIDTH = "320px";
export const HISTOGRAM_SIZE = { width: 308, height: 120 };
export const MAX_BIN_COUNT = 50;
