const PRIMARY_FAMILY = 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif';
const MONO_FAMILY = '"Lucida Console", Monaco, monospace';
const FONT_SCALE = {
  PRIMARY_FAMILY,
  MONO_FAMILY,
  "100": {
    fontFamily: PRIMARY_FAMILY,
    fontSize: "12px",
    fontWeight: "normal",
    lineHeight: "20px",
  },
  "150": {
    fontFamily: PRIMARY_FAMILY,
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "16px",
  },
  "200": {
    fontFamily: PRIMARY_FAMILY,
    fontSize: "14px",
    fontWeight: "normal",
    lineHeight: "20px",
  },
  "250": {
    fontFamily: PRIMARY_FAMILY,
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "16px",
  },
  "300": {
    fontFamily: PRIMARY_FAMILY,
    fontSize: "16px",
    fontWeight: "normal",
    lineHeight: "24px",
  },
  "350": {
    fontFamily: PRIMARY_FAMILY,
    fontSize: "16px",
    fontWeight: 500,
    lineHeight: "20px",
  },
  "400": {
    fontFamily: PRIMARY_FAMILY,
    fontSize: "18px",
    fontWeight: "normal",
    lineHeight: "28px",
  },
  "450": {
    fontFamily: PRIMARY_FAMILY,
    fontSize: "18px",
    fontWeight: 500,
    lineHeight: "24px",
  },
  "550": {
    fontFamily: PRIMARY_FAMILY,
    fontSize: "20px",
    fontWeight: 500,
    lineHeight: "28px",
  },
  "650": {
    fontFamily: PRIMARY_FAMILY,
    fontSize: "24px",
    fontWeight: 500,
    lineHeight: "32px",
  },
  "750": {
    fontFamily: PRIMARY_FAMILY,
    fontSize: "28px",
    fontWeight: 500,
    lineHeight: "36px",
  },
  "850": {
    fontFamily: PRIMARY_FAMILY,
    fontSize: "32px",
    fontWeight: 500,
    lineHeight: "40px",
  },
  "950": {
    fontFamily: PRIMARY_FAMILY,
    fontSize: "36px",
    fontWeight: 500,
    lineHeight: "44px",
  },
  "1050": {
    fontFamily: PRIMARY_FAMILY,
    fontSize: "40px",
    fontWeight: 500,
    lineHeight: "52px",
  },
  "1150": {
    fontFamily: PRIMARY_FAMILY,
    fontSize: "36px",
    fontWeight: 500,
    lineHeight: "44px",
  },
  "1250": {
    fontFamily: PRIMARY_FAMILY,
    fontSize: "44px",
    fontWeight: 500,
    lineHeight: "52px",
  },
  "1350": {
    fontFamily: PRIMARY_FAMILY,
    fontSize: "52px",
    fontWeight: 500,
    lineHeight: "64px",
  },
  "1450": {
    fontFamily: PRIMARY_FAMILY,
    fontSize: "96px",
    fontWeight: 500,
    lineHeight: "112px",
  },
} as const;

export const LightTheme = {
  name: "light-theme",
  colors: {
    // colorTokens
    primaryA: "#000",
    primaryB: "#FFF",
    primary: "#000",
    primary50: "#F6F6F6",
    primary100: "#EEE",
    primary200: "#E2E2E2",
    primary300: "#CBCBCB",
    primary400: "#AFAFAF",
    primary500: "#6B6B6B",
    primary600: "#545454",
    primary700: "#333",
    accent: "#276EF1",
    accent50: "#EFF3FE",
    accent100: "#D4E2FC",
    accent200: "#A0BFF8",
    accent300: "#5B91F5",
    accent400: "#276EF1",
    accent500: "#1E54B7",
    accent600: "#174291",
    accent700: "#102C60",
    negative: "#E11900",
    negative50: "#FFEFED",
    negative100: "#FED7D2",
    negative200: "#F1998E",
    negative300: "#E85C4A",
    negative400: "#E11900",
    negative500: "#AB1300",
    negative600: "#870F00",
    negative700: "#5A0A00",
    warning: "#FFC043",
    warning50: "#FFFAF0",
    warning100: "#FFF2D9",
    warning200: "#FFE3AC",
    warning300: "#FFCF70",
    warning400: "#FFC043",
    warning500: "#BC8B2C",
    warning600: "#996F00",
    warning700: "#674D1B",
    positive: "#03703C",
    positive50: "#E6F2ED",
    positive100: "#ADDEC9",
    positive200: "#66D19E",
    positive300: "#06C167",
    positive400: "#048848",
    positive500: "#03703C",
    positive600: "#03582F",
    positive700: "#10462D",
    white: "#FFF",
    black: "#000",
    mono100: "#FFF",
    mono200: "#F6F6F6",
    mono300: "#EEE",
    mono400: "#E2E2E2",
    mono500: "#CBCBCB",
    mono600: "#AFAFAF",
    mono700: "#6B6B6B",
    mono800: "#545454",
    mono900: "#333",
    mono1000: "#000",
    ratingInactiveFill: "#EEE",
    ratingStroke: "#CBCBCB",
    // component
    buttonPrimaryFill: "#000",
    buttonPrimaryText: "#FFF",
    buttonPrimaryHover: "#333",
    buttonPrimaryActive: "#545454",
    buttonPrimarySelectedFill: "#545454",
    buttonPrimarySelectedText: "#FFF",
    buttonPrimarySpinnerForeground: "#276EF1",
    buttonPrimarySpinnerBackground: "#FFF",
    buttonSecondaryFill: "#EEE",
    buttonSecondaryText: "#000",
    buttonSecondaryHover: "#E2E2E2",
    buttonSecondaryActive: "#CBCBCB",
    buttonSecondarySelectedFill: "#CBCBCB",
    buttonSecondarySelectedText: "#000",
    buttonSecondarySpinnerForeground: "#276EF1",
    buttonSecondarySpinnerBackground: "#FFF",
    buttonTertiaryFill: "transparent",
    buttonTertiaryText: "#000",
    buttonTertiaryHover: "#F6F6F6",
    buttonTertiaryActive: "#EEE",
    buttonTertiarySelectedFill: "#EEE",
    buttonTertiarySelectedText: "#000",
    buttonTertiaryDisabledActiveFill: "#F6F6F6",
    buttonTertiaryDisabledActiveText: "#AFAFAF",
    buttonTertiarySpinnerForeground: "#276EF1",
    buttonTertiarySpinnerBackground: "#EEE",
    buttonDisabledFill: "#F6F6F6",
    buttonDisabledText: "#AFAFAF",
    buttonDisabledActiveFill: "#6B6B6B",
    buttonDisabledActiveText: "#FFF",
    buttonDisabledSpinnerForeground: "#AFAFAF",
    buttonDisabledSpinnerBackground: "#E2E2E2",
    breadcrumbsText: "#333",
    breadcrumbsSeparatorFill: "#6B6B6B",
    calendarBackground: "#FFF",
    calendarForeground: "#000",
    calendarForegroundDisabled: "#CBCBCB",
    calendarHeaderBackground: "#FFF",
    calendarHeaderForeground: "#000",
    calendarHeaderBackgroundActive: "#333",
    calendarHeaderForegroundDisabled: "#6B6B6B",
    calendarDayForegroundPseudoSelected: "#000",
    calendarDayBackgroundPseudoSelectedHighlighted: "#E2E2E2",
    calendarDayForegroundPseudoSelectedHighlighted: "#000",
    calendarDayBackgroundSelected: "#000",
    calendarDayForegroundSelected: "#FFF",
    calendarDayBackgroundSelectedHighlighted: "#000",
    calendarDayForegroundSelectedHighlighted: "#FFF",
    comboboxListItemFocus: "#F6F6F6",
    comboboxListItemHover: "#EEE",
    fileUploaderBackgroundColor: "#F6F6F6",
    fileUploaderBackgroundColorActive: "#F6F6F6",
    fileUploaderBorderColorActive: "#000",
    fileUploaderBorderColorDefault: "#CBCBCB",
    fileUploaderMessageColor: "#545454",
    linkText: "#000",
    linkVisited: "#333",
    linkHover: "#545454",
    linkActive: "#6B6B6B",
    listHeaderFill: "#FFF",
    listBodyFill: "#FFF",
    progressStepsCompletedText: "#FFF",
    progressStepsCompletedFill: "#000",
    progressStepsActiveText: "#FFF",
    progressStepsActiveFill: "#000",
    toggleFill: "#FFF",
    toggleFillChecked: "#000",
    toggleFillDisabled: "#AFAFAF",
    toggleTrackFill: "#E2E2E2",
    toggleTrackFillDisabled: "#EEE",
    tickFill: "#FFF",
    tickFillHover: "#F6F6F6",
    tickFillActive: "#EEE",
    tickFillSelected: "#000",
    tickFillSelectedHover: "#333",
    tickFillSelectedHoverActive: "#545454",
    tickFillError: "#FFEFED",
    tickFillErrorHover: "#FED7D2",
    tickFillErrorHoverActive: "#F1998E",
    tickFillErrorSelected: "#E11900",
    tickFillErrorSelectedHover: "#AB1300",
    tickFillErrorSelectedHoverActive: "#870F00",
    tickFillDisabled: "#AFAFAF",
    tickBorder: "#6B6B6B",
    tickBorderError: "#E11900",
    tickMarkFill: "#FFF",
    tickMarkFillError: "#FFF",
    tickMarkFillDisabled: "#FFF",
    sliderTrackFill: "transparent",
    sliderHandleFill: "#000",
    sliderHandleFillDisabled: "#AFAFAF",
    sliderHandleInnerFill: "#000",
    sliderTrackFillHover: "#CBCBCB",
    sliderTrackFillActive: "#AFAFAF",
    sliderTrackFillDisabled: "#EEE",
    sliderHandleInnerFillDisabled: "#E2E2E2",
    sliderHandleInnerFillSelectedHover: "#000",
    sliderHandleInnerFillSelectedActive: "#6B6B6B",
    inputBorder: "#EEE",
    inputFill: "#EEE",
    inputFillError: "#FFEFED",
    inputFillDisabled: "#F6F6F6",
    inputFillActive: "#F6F6F6",
    inputFillPositive: "#E6F2ED",
    inputTextDisabled: "#AFAFAF",
    inputBorderError: "#F1998E",
    inputBorderPositive: "#66D19E",
    inputEnhancerFill: "#EEE",
    inputEnhancerFillDisabled: "#EEE",
    inputEnhancerTextDisabled: "#AFAFAF",
    inputPlaceholder: "#6B6B6B",
    inputPlaceholderDisabled: "#AFAFAF",
    menuFill: "#FFF",
    menuFillHover: "#F6F6F6",
    menuFontDefault: "#545454",
    menuFontDisabled: "#CBCBCB",
    menuFontHighlighted: "#000",
    menuFontSelected: "#000",
    modalCloseColor: "#000",
    modalCloseColorHover: "#545454",
    modalCloseColorFocus: "#545454",
    tabBarFill: "#F6F6F6",
    tabColor: "#545454",
    notificationInfoBackground: "#EFF3FE",
    notificationInfoText: "#000",
    notificationPositiveBackground: "#E6F2ED",
    notificationPositiveText: "#000",
    notificationWarningBackground: "#FFFAF0",
    notificationWarningText: "#000",
    notificationNegativeBackground: "#FFEFED",
    notificationNegativeText: "#000",
    tagFontDisabledRampUnit: "100",
    tagSolidFontRampUnit: "0",
    tagSolidRampUnit: "400",
    tagOutlinedFontRampUnit: "400",
    tagOutlinedRampUnit: "200",
    tagSolidHoverRampUnit: "50",
    tagSolidActiveRampUnit: "100",
    tagSolidDisabledRampUnit: "50",
    tagSolidFontHoverRampUnit: "500",
    tagLightRampUnit: "50",
    tagLightHoverRampUnit: "100",
    tagLightActiveRampUnit: "100",
    tagLightFontRampUnit: "500",
    tagLightFontHoverRampUnit: "500",
    tagOutlinedHoverRampUnit: "50",
    tagOutlinedActiveRampUnit: "0",
    tagOutlinedFontHoverRampUnit: "400",
    tagNeutralFontDisabled: "#AFAFAF",
    tagNeutralOutlinedDisabled: "#E2E2E2",
    tagNeutralSolidFont: "#FFF",
    tagNeutralSolidBackground: "#000",
    tagNeutralOutlinedBackground: "#AFAFAF",
    tagNeutralOutlinedFont: "#000",
    tagNeutralSolidHover: "#EEE",
    tagNeutralSolidActive: "#E2E2E2",
    tagNeutralSolidDisabled: "#F6F6F6",
    tagNeutralSolidFontHover: "#333",
    tagNeutralLightBackground: "#EEE",
    tagNeutralLightHover: "#EEE",
    tagNeutralLightActive: "#E2E2E2",
    tagNeutralLightDisabled: "#F6F6F6",
    tagNeutralLightFont: "#333",
    tagNeutralLightFontHover: "#333",
    tagNeutralOutlinedActive: "#333",
    tagNeutralOutlinedFontHover: "#545454",
    tagNeutralOutlinedHover: hexToRgba("#000", "0.08"),
    tagPrimaryFontDisabled: "#AFAFAF",
    tagPrimaryOutlinedDisabled: "#E2E2E2",
    tagPrimarySolidFont: "#FFF",
    tagPrimarySolidBackground: "#000",
    tagPrimaryOutlinedFontHover: "#000",
    tagPrimaryOutlinedFont: "#000",
    tagPrimarySolidHover: "#EEE",
    tagPrimarySolidActive: "#E2E2E2",
    tagPrimarySolidDisabled: "#F6F6F6",
    tagPrimarySolidFontHover: "#333",
    tagPrimaryLightBackground: "#F6F6F6",
    tagPrimaryLightHover: "#EEE",
    tagPrimaryLightActive: "#EEE",
    tagPrimaryLightDisabled: "#F6F6F6",
    tagPrimaryLightFont: "#6B6B6B",
    tagPrimaryLightFontHover: "#6B6B6B",
    tagPrimaryOutlinedActive: "#545454",
    tagPrimaryOutlinedHover: hexToRgba("#000", "0.08"),
    tagPrimaryOutlinedBackground: "#AFAFAF",
    tagAccentFontDisabled: "#A0BFF8",
    tagAccentOutlinedDisabled: "#A0BFF8",
    tagAccentSolidFont: "#FFF",
    tagAccentSolidBackground: "#276EF1",
    tagAccentOutlinedBackground: "#A0BFF8",
    tagAccentOutlinedFont: "#276EF1",
    tagAccentSolidHover: "#EFF3FE",
    tagAccentSolidActive: "#D4E2FC",
    tagAccentSolidDisabled: "#EFF3FE",
    tagAccentSolidFontHover: "#1E54B7",
    tagAccentLightBackground: "#EFF3FE",
    tagAccentLightHover: "#D4E2FC",
    tagAccentLightActive: "#D4E2FC",
    tagAccentLightDisabled: "#EFF3FE",
    tagAccentLightFont: "#1E54B7",
    tagAccentLightFontHover: "#1E54B7",
    tagAccentOutlinedActive: "#174291",
    tagAccentOutlinedFontHover: "#276EF1",
    tagAccentOutlinedHover: hexToRgba("#000", "0.08"),
    tagPositiveFontDisabled: "#66D19E",
    tagPositiveOutlinedDisabled: "#66D19E",
    tagPositiveSolidFont: "#FFF",
    tagPositiveSolidBackground: "#048848",
    tagPositiveOutlinedBackground: "#66D19E",
    tagPositiveOutlinedFont: "#048848",
    tagPositiveSolidHover: "#E6F2ED",
    tagPositiveSolidActive: "#ADDEC9",
    tagPositiveSolidDisabled: "#E6F2ED",
    tagPositiveSolidFontHover: "#03703C",
    tagPositiveLightBackground: "#E6F2ED",
    tagPositiveLightHover: "#ADDEC9",
    tagPositiveLightActive: "#ADDEC9",
    tagPositiveLightDisabled: "#E6F2ED",
    tagPositiveLightFont: "#03703C",
    tagPositiveLightFontHover: "#03703C",
    tagPositiveOutlinedActive: "#03582F",
    tagPositiveOutlinedFontHover: "#048848",
    tagPositiveOutlinedHover: hexToRgba("#000", "0.08"),
    tagWarningFontDisabled: "#FFCF70",
    tagWarningOutlinedDisabled: "#FFCF70",
    tagWarningSolidFont: "#674D1B",
    tagWarningSolidBackground: "#FFC043",
    tagWarningOutlinedBackground: "#FFCF70",
    tagWarningOutlinedFont: "#996F00",
    tagWarningSolidHover: "#FFFAF0",
    tagWarningSolidActive: "#FFF2D9",
    tagWarningSolidDisabled: "#FFFAF0",
    tagWarningSolidFontHover: "#BC8B2C",
    tagWarningLightBackground: "#FFFAF0",
    tagWarningLightHover: "#FFF2D9",
    tagWarningLightActive: "#FFF2D9",
    tagWarningLightDisabled: "#FFFAF0",
    tagWarningLightFont: "#BC8B2C",
    tagWarningLightFontHover: "#BC8B2C",
    tagWarningOutlinedActive: "#996F00",
    tagWarningOutlinedFontHover: "#996F00",
    tagWarningOutlinedHover: hexToRgba("#000", "0.08"),
    tagNegativeFontDisabled: "#F1998E",
    tagNegativeOutlinedDisabled: "#F1998E",
    tagNegativeSolidFont: "#FFF",
    tagNegativeSolidBackground: "#E11900",
    tagNegativeOutlinedBackground: "#F1998E",
    tagNegativeOutlinedFont: "#E11900",
    tagNegativeSolidHover: "#FFEFED",
    tagNegativeSolidActive: "#FED7D2",
    tagNegativeSolidDisabled: "#FFEFED",
    tagNegativeSolidFontHover: "#AB1300",
    tagNegativeLightBackground: "#FFEFED",
    tagNegativeLightHover: "#FED7D2",
    tagNegativeLightActive: "#FED7D2",
    tagNegativeLightDisabled: "#FFEFED",
    tagNegativeLightFont: "#AB1300",
    tagNegativeLightFontHover: "#AB1300",
    tagNegativeOutlinedActive: "#870F00",
    tagNegativeOutlinedFontHover: "#E11900",
    tagNegativeOutlinedHover: hexToRgba("#000", "0.08"),
    tableHeadBackgroundColor: "#FFF",
    tableBackground: "#FFF",
    tableStripedBackground: "#F6F6F6",
    tableFilter: "#AFAFAF",
    tableFilterHeading: "#6B6B6B",
    tableFilterBackground: "#FFF",
    tableFilterFooterBackground: "#F6F6F6",
    toastText: "#FFF",
    toastPrimaryText: "#FFF",
    toastInfoBackground: "#276EF1",
    toastInfoText: "#FFF",
    toastPositiveBackground: "#048848",
    toastPositiveText: "#FFF",
    toastWarningBackground: "#FFC043",
    toastWarningText: "#000",
    toastNegativeBackground: "#E11900",
    toastNegativeText: "#FFF",
    spinnerTrackFill: "#333",
    progressbarTrackFill: "#333",
    tooltipBackground: "#333",
    tooltipText: "#FFF",

    // core
    backgroundPrimary: "#FFF",
    backgroundSecondary: "#F6F6F6",
    backgroundTertiary: "#EEE",
    backgroundInversePrimary: "#000",
    backgroundInverseSecondary: "#1F1F1F",
    contentPrimary: "#000",
    contentSecondary: "#545454",
    contentTertiary: "#6B6B6B",
    contentInversePrimary: "#FFF",
    contentInverseSecondary: "#CBCBCB",
    contentInverseTertiary: "#AFAFAF",
    borderOpaque: "#E2E2E2",
    borderTransparent: hexToRgba("#000", "0.08"),
    borderSelected: "#000",
    borderInverseOpaque: "#333",
    borderInverseTransparent: hexToRgba("#FFF", "0.2"),
    borderInverseSelected: "#FFF",
    // core extensions
    backgroundStateDisabled: "#F6F6F6",
    backgroundOverlayDark: hexToRgba("#000", "0.3"),
    backgroundOverlayLight: hexToRgba("#000", "0.08"),
    backgroundAccent: "#276EF1",
    backgroundNegative: "#E11900",
    backgroundWarning: "#FFC043",
    backgroundPositive: "#048848",
    backgroundLightAccent: "#EFF3FE",
    backgroundLightNegative: "#FFEFED",
    backgroundLightWarning: "#FFFAF0",
    backgroundLightPositive: "#E6F2ED",
    backgroundAlwaysDark: "#000",
    backgroundAlwaysLight: "#FFF",
    contentStateDisabled: "#AFAFAF",
    contentAccent: "#276EF1",
    contentOnColor: "#FFF",
    contentOnColorInverse: "#000",
    contentNegative: "#E11900",
    contentWarning: "#996F00",
    contentPositive: "#048848",
    borderStateDisabled: "#F6F6F6",
    borderAccent: "#276EF1",
    borderAccentLight: "#A0BFF8",
    borderNegative: "#F1998E",
    borderWarning: "#FFE3AC",
    borderPositive: "#66D19E",
  },
  animation: {
    timing100: "100ms",
    timing200: "200ms",
    timing300: "300ms",
    timing400: "400ms",
    timing500: "500ms",
    timing600: "600ms",
    timing700: "700ms",
    timing800: "800ms",
    timing900: "900ms",
    timing1000: "1000ms",
    easeInCurve: "cubic-bezier(.8, .2, .6, 1)",
    easeOutCurve: "cubic-bezier(.2, .8, .4, 1)",
    easeInOutCurve: "cubic-bezier(0.4, 0, 0.2, 1)",
    easeInQuinticCurve: "cubic-bezier(0.755, 0.05, 0.855, 0.06)",
    easeOutQuinticCurve: "cubic-bezier(0.23, 1, 0.32, 1)",
    easeInOutQuinticCurve: "cubic-bezier(0.86, 0, 0.07, 1)",
    linearCurve: "cubic-bezier(0, 0, 1, 1)",
  },
  breakpoints: {
    small: 320,
    medium: 600,
    large: 1136,
  },
  mediaQuery: {
    small: "@media screen and (min-width: 320px)",
    medium: "@media screen and (min-width: 600px)",
    large: "@media screen and (min-width: 1136px)",
  },
  borders: {
    border100: {
      borderColor: "rgba(0, 0, 0, 0.04)",
      borderStyle: "solid",
      borderWidth: "1px",
    },
    border200: {
      borderColor: "rgba(0, 0, 0, 0.08)",
      borderStyle: "solid",
      borderWidth: "1px",
    },
    border300: {
      borderColor: "rgba(0, 0, 0, 0.12)",
      borderStyle: "solid",
      borderWidth: "1px",
    },
    border400: {
      borderColor: "rgba(0, 0, 0, 0.16)",
      borderStyle: "solid",
      borderWidth: "1px",
    },
    border500: {
      borderColor: "rgba(0, 0, 0, 0.2)",
      borderStyle: "solid",
      borderWidth: "1px",
    },
    border600: {
      borderColor: "rgba(0, 0, 0, 0.24)",
      borderStyle: "solid",
      borderWidth: "1px",
    },
    radius100: "2px",
    radius200: "4px",
    radius300: "8px",
    radius400: "12px",
    radius500: "16px",
    useRoundedCorners: true,
    buttonBorderRadius: "0px",
    inputBorderRadius: "0px",
    popoverBorderRadius: "0px",
    surfaceBorderRadius: "0px",
    tagBorderRadius: "24px",
  },
  direction: "auto",
  grid: {
    columns: [4, 8, 12],
    gutters: [16, 36, 36],
    margins: [16, 36, 64],
    gaps: 0,
    unit: "px",
    maxWidth: 1280,
  },
  lighting: {
    shadow400: "0 1px 4px rgba(0, 0, 0, 0.16)",
    shadow500: "0 2px 8px rgba(0, 0, 0, 0.16)",
    shadow600: "0 4px 16px rgba(0, 0, 0, 0.16)",
    shadow700: "0 8px 24px rgba(0, 0, 0, 0.16)",
    overlay0: "inset 0 0 0 1000px rgba(0, 0, 0, 0)",
    overlay100: "inset 0 0 0 1000px rgba(0, 0, 0, 0.04)",
    overlay200: "inset 0 0 0 1000px rgba(0, 0, 0, 0.08)",
    overlay300: "inset 0 0 0 1000px rgba(0, 0, 0, 0.12)",
    overlay400: "inset 0 0 0 1000px rgba(0, 0, 0, 0.16)",
    overlay500: "inset 0 0 0 1000px rgba(0, 0, 0, 0.2)",
    overlay600: "inset 0 0 0 1000px rgba(0, 0, 0, 0.24)",
    shallowAbove: "0px -4px 16px rgba(0, 0, 0, 0.12)",
    shallowBelow: "0px 4px 16px rgba(0, 0, 0, 0.12)",
    deepAbove: "0px -16px 48px rgba(0, 0, 0, 0.22)",
    deepBelow: "0px 16px 48px rgba(0, 0, 0, 0.22)",
  },
  sizing: {
    scale0: "2px",
    scale100: "4px",
    scale200: "6px",
    scale300: "8px",
    scale400: "10px",
    scale500: "12px",
    scale550: "14px",
    scale600: "16px",
    scale650: "18px",
    scale700: "20px",
    scale750: "22px",
    scale800: "24px",
    scale850: "28px",
    scale900: "32px",
    scale950: "36px",
    scale1000: "40px",
    scale1200: "48px",
    scale1400: "56px",
    scale1600: "64px",
    scale2400: "96px",
    scale3200: "128px",
    scale4800: "192px",
  },
  typography: {
    font100: FONT_SCALE["100"],
    font150: FONT_SCALE["150"],
    font200: FONT_SCALE["200"],
    font250: FONT_SCALE["250"],
    font300: FONT_SCALE["300"],
    font350: FONT_SCALE["350"],
    font400: FONT_SCALE["400"],
    font450: FONT_SCALE["450"],
    font550: FONT_SCALE["550"],
    font650: FONT_SCALE["650"],
    font750: FONT_SCALE["750"],
    font850: FONT_SCALE["850"],
    font950: FONT_SCALE["950"],
    font1050: FONT_SCALE["1050"],
    font1150: FONT_SCALE["1150"],
    font1250: FONT_SCALE["1250"],
    font1350: FONT_SCALE["1350"],
    font1450: FONT_SCALE["1450"],
    ParagraphXSmall: FONT_SCALE["100"],
    ParagraphSmall: FONT_SCALE["200"],
    ParagraphMedium: FONT_SCALE["300"],
    ParagraphLarge: FONT_SCALE["400"],
    LabelXSmall: FONT_SCALE["150"],
    LabelSmall: FONT_SCALE["250"],
    LabelMedium: FONT_SCALE["350"],
    LabelLarge: FONT_SCALE["450"],
    HeadingXSmall: FONT_SCALE["550"],
    HeadingSmall: FONT_SCALE["650"],
    HeadingMedium: FONT_SCALE["750"],
    HeadingLarge: FONT_SCALE["850"],
    HeadingXLarge: FONT_SCALE["950"],
    HeadingXXLarge: FONT_SCALE["1050"],
    DisplayXSmall: FONT_SCALE["1150"],
    DisplaySmall: FONT_SCALE["1250"],
    DisplayMedium: FONT_SCALE["1350"],
    DisplayLarge: FONT_SCALE["1450"],
    MonoParagraphXSmall: { ...FONT_SCALE["100"], fontFamily: MONO_FAMILY },
    MonoParagraphSmall: { ...FONT_SCALE["200"], fontFamily: MONO_FAMILY },
    MonoParagraphMedium: { ...FONT_SCALE["300"], fontFamily: MONO_FAMILY },
    MonoParagraphLarge: { ...FONT_SCALE["400"], fontFamily: MONO_FAMILY },
    MonoLabelXSmall: { ...FONT_SCALE["150"], fontFamily: MONO_FAMILY },
    MonoLabelSmall: { ...FONT_SCALE["250"], fontFamily: MONO_FAMILY },
    MonoLabelMedium: { ...FONT_SCALE["350"], fontFamily: MONO_FAMILY },
    MonoLabelLarge: { ...FONT_SCALE["450"], fontFamily: MONO_FAMILY },
    MonoHeadingXSmall: { ...FONT_SCALE["550"], fontFamily: MONO_FAMILY },
    MonoHeadingSmall: { ...FONT_SCALE["650"], fontFamily: MONO_FAMILY },
    MonoHeadingMedium: { ...FONT_SCALE["750"], fontFamily: MONO_FAMILY },
    MonoHeadingLarge: { ...FONT_SCALE["850"], fontFamily: MONO_FAMILY },
    MonoHeadingXLarge: { ...FONT_SCALE["950"], fontFamily: MONO_FAMILY },
    MonoHeadingXXLarge: { ...FONT_SCALE["1050"], fontFamily: MONO_FAMILY },
    MonoDisplayXSmall: { ...FONT_SCALE["1150"], fontFamily: MONO_FAMILY },
    MonoDisplaySmall: { ...FONT_SCALE["1250"], fontFamily: MONO_FAMILY },
    MonoDisplayMedium: { ...FONT_SCALE["1350"], fontFamily: MONO_FAMILY },
    MonoDisplayLarge: { ...FONT_SCALE["1450"], fontFamily: MONO_FAMILY },
  },
  zIndex: {
    modal: 2e3,
  },
};
